package minitype;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.io.IOException;

/**
 * Main — the driver that runs the full course pipeline on a .mt source file:
 *
 *     source --(MiniTypeLexer)--> tokens --(MiniTypeParser)--> parse tree
 *            --(TypeChecker = SDD)--> type errors / success
 *
 * Usage:  java minitype.Main <file.mt> [--tree]
 *   --tree   also print the parse tree (handy for demos / the AST topic).
 *
 * Exit code: 0 if type checking succeeds, 1 if there are syntax or type errors,
 *            2 on usage error.
 */
public final class Main {

    public static void main(String[] args) throws IOException {
        if (args.length < 1) {
            System.err.println("usage: java minitype.Main <file.mt> [--tree]");
            System.exit(2);
        }
        String path = args[0];
        boolean showTree = args.length > 1 && args[1].equals("--tree");

        // 1. Lexer + parser (generated by ANTLR from MiniType.g4).
        CharStream input = CharStreams.fromFileName(path);
        MiniTypeLexer lexer = new MiniTypeLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        MiniTypeParser parser = new MiniTypeParser(tokens);

        // Count syntax errors ourselves so we can skip type checking if the
        // program does not even parse.
        SyntaxErrorCounter syntax = new SyntaxErrorCounter();
        lexer.removeErrorListeners();  lexer.addErrorListener(syntax);
        parser.removeErrorListeners(); parser.addErrorListener(syntax);

        ParseTree tree;
        try {
            tree = parser.program();
        } catch (StackOverflowError e) {
            // Pathologically deep nesting overflows the parser's recursion.
            System.err.println("error: input is too deeply nested to parse.");
            System.exit(1);
            return;
        }

        if (showTree) {
            System.out.println("--- parse tree ---");
            printTree(tree, parser, "");
            System.out.println("------------------");
        }

        if (syntax.count > 0) {
            System.err.println("Parsing FAILED with " + syntax.count + " syntax error(s); skipping type check.");
            System.exit(1);
        }

        // 2. Type checking = the SDD over the parse tree.
        Diagnostics diag = new Diagnostics();
        try {
            new TypeChecker(diag).visit(tree);
        } catch (StackOverflowError e) {
            // The SDD walks the tree recursively; extreme depth overflows the stack.
            System.err.println("error: input is too deeply nested to type-check.");
            System.exit(1);
            return;
        }

        // 3. Report.
        System.out.println("=== Type checking: " + path + " ===");
        if (diag.hasErrors()) {
            for (String e : diag.all()) System.out.println(e);
            System.out.println("Type checking FAILED with " + diag.count() + " type error(s).");
            System.exit(1);
        }
        System.out.println("Type checking SUCCEEDED. No type errors.");
        System.exit(0);
    }

    /** Pretty-print the parse tree: rule/label names for inner nodes, quoted text for leaves. */
    private static void printTree(ParseTree t, Parser parser, String indent) {
        String label = (t instanceof TerminalNode)
                ? "'" + t.getText() + "'"
                : t.getClass().getSimpleName().replace("Context", ""); // shows the # label, e.g. AddSub
        System.out.println(indent + label);
        for (int i = 0; i < t.getChildCount(); i++)
            printTree(t.getChild(i), parser, indent + "  ");
    }

    /** Collects (and prints) ANTLR syntax errors. */
    static final class SyntaxErrorCounter extends BaseErrorListener {
        int count = 0;
        @Override public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol,
                                          int line, int charPositionInLine, String msg, RecognitionException e) {
            count++;
            System.err.println(line + ":" + (charPositionInLine + 1) + ": syntax error: " + msg);
        }
    }
}
